services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  spark-master:
    image: spark:3.5.7-java17-python3
    container_name: spark_master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./scripts:/opt/spark/jobs
      - ./data:/opt/spark/data

  spark-worker:
    image: spark:3.5.7-java17-python3
    container_name: spark_worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./scripts:/opt/spark/jobs
      - ./data:/opt/spark/data
    

  airflow-init:
    image: apache/airflow:2.9.0
    container_name: airflow_init
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install -r /requirements.txt &&
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Tori
      --lastname Celebrezze
      --role Admin
      --email tori@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - airflow-init
      - spark-master
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "pip install -r /requirements.txt && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
      - spark-master
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "pip install -r /requirements.txt && airflow scheduler"

volumes:
  postgres_data: